/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionPanel: typeof import('./../components/core/dev-setting/components/action-panel.vue')['default']
    ApprovalFlow: typeof import('./../components/business/approval-flow.vue')['default']
    DebugPanel: typeof import('./../components/core/dev-setting/components/debug-panel.vue')['default']
    DevicePanel: typeof import('./../components/core/dev-setting/components/device-panel.vue')['default']
    DevSetting: typeof import('./../components/core/dev-setting/index.vue')['default']
    EnvPanel: typeof import('./../components/core/dev-setting/components/env-panel.vue')['default']
    RoutePanel: typeof import('./../components/core/dev-setting/components/route-panel.vue')['default']
    StoragePanel: typeof import('./../components/core/dev-setting/components/storage-panel.vue')['default']
  }
}
