/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoBlock: typeof import('./../components/demo-block/demo-block.vue')['default']
    DemoPage: typeof import('./../components/demo-page/demo-page.vue')['default']
    DemoSection: typeof import('./../components/demo-section/demo-section.vue')['default']
  }
}
