/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/demo/index" |
  "/pages/demo/button/index" |
  "/pages/demo/cell/index" |
  "/pages/demo/checkbox/index" |
  "/pages/demo/dialog/index" |
  "/pages/demo/icon/index" |
  "/pages/demo/input/index" |
  "/pages/demo/loading/index" |
  "/pages/demo/popup/index" |
  "/pages/demo/switch/index" |
  "/pages/demo/tag/index" |
  "/pages/demo/toast/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
