/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/tabbar/home/index" |
  "/pages/demo/index" |
  "/pages/demo/action-sheet/index" |
  "/pages/demo/arc/index" |
  "/pages/demo/avatar/index" |
  "/pages/demo/avatar-group/index" |
  "/pages/demo/back-top/index" |
  "/pages/demo/badge/index" |
  "/pages/demo/button/index" |
  "/pages/demo/calendar/index" |
  "/pages/demo/card/index" |
  "/pages/demo/cascader/index" |
  "/pages/demo/cell/index" |
  "/pages/demo/cell-group/index" |
  "/pages/demo/checkbox/index" |
  "/pages/demo/checkbox-group/index" |
  "/pages/demo/collapse/index" |
  "/pages/demo/config-provider/index" |
  "/pages/demo/countdown/index" |
  "/pages/demo/date-picker/index" |
  "/pages/demo/date-range-select/index" |
  "/pages/demo/date-select/index" |
  "/pages/demo/dialog/index" |
  "/pages/demo/dropdown-item/index" |
  "/pages/demo/dropdown-menu/index" |
  "/pages/demo/empty/index" |
  "/pages/demo/field/index" |
  "/pages/demo/float-button/index" |
  "/pages/demo/footer/index" |
  "/pages/demo/form/index" |
  "/pages/demo/form-item/index" |
  "/pages/demo/header/index" |
  "/pages/demo/icon/index" |
  "/pages/demo/image/index" |
  "/pages/demo/index-anchor/index" |
  "/pages/demo/index-bar/index" |
  "/pages/demo/input/index" |
  "/pages/demo/keyboard/index" |
  "/pages/demo/layout/index" |
  "/pages/demo/line/index" |
  "/pages/demo/loading/index" |
  "/pages/demo/navbar/index" |
  "/pages/demo/navbar-gradient/index" |
  "/pages/demo/noticebar/index" |
  "/pages/demo/notify/index" |
  "/pages/demo/number-roll/index" |
  "/pages/demo/overlay/index" |
  "/pages/demo/pagination/index" |
  "/pages/demo/picker/index" |
  "/pages/demo/picker-panel/index" |
  "/pages/demo/popover/index" |
  "/pages/demo/popup/index" |
  "/pages/demo/poster/index" |
  "/pages/demo/progress/index" |
  "/pages/demo/pull-refresh/index" |
  "/pages/demo/qrcode/index" |
  "/pages/demo/radio/index" |
  "/pages/demo/radio-group/index" |
  "/pages/demo/rate/index" |
  "/pages/demo/resize/index" |
  "/pages/demo/safe-area/index" |
  "/pages/demo/search/index" |
  "/pages/demo/select/index" |
  "/pages/demo/sidebar/index" |
  "/pages/demo/skeleton/index" |
  "/pages/demo/slider/index" |
  "/pages/demo/stepper/index" |
  "/pages/demo/steps/index" |
  "/pages/demo/sticky/index" |
  "/pages/demo/swipe-cell/index" |
  "/pages/demo/swiper/index" |
  "/pages/demo/switch/index" |
  "/pages/demo/tabbar/index" |
  "/pages/demo/tabbar-item/index" |
  "/pages/demo/tabs/index" |
  "/pages/demo/tag/index" |
  "/pages/demo/text/index" |
  "/pages/demo/text-highlight/index" |
  "/pages/demo/textarea/index" |
  "/pages/demo/toast/index" |
  "/pages/demo/transition/index" |
  "/pages/demo/upload/index" |
  "/pages/tabbar/about/index" |
  "/pages/tabbar/components/index" |
  "/pages/tabbar/templates/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/tabbar/home/index" | "/pages/tabbar/components/index" | "/pages/tabbar/templates/index" | "/pages/tabbar/about/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
